name: 'Thore Voiceover '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23431485844776034
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.75
  lightness: 0.375
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
